site_name: Koinos Docs
site_url: https://docs.koinos.io

site_description: Documentaion for Koinos, the world's first free to use blockchain

repo_name: koinos/koinos
repo_url: https://github.com/koinos/koinos

#edit_uri: blob/master/docs

copyright: Copyright &copy;2023 - Koinos Group

theme:
  name: material
  icon:
    edit: material/pencil
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: fark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  font:
    text: Space Grotesk
    code: Space Mono
  favicon: assets/koinos-icon-dark.png
  logo: assets/koinos-mark-light.svg

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/koinos
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/koinos/
    - icon: fontawesome/brands/discord
      link: https://discord.koinos.io
    - icon: fontawesome/brands/telegram
      link: https://t.me/koinos_community
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheKoinosGroup
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@koinosgroup

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Quickstart:
    - Running a Koinos Node: quickstart/running-a-koinos-node.md
    - Block Production: quickstart/block-production.md
    - Developer Guide: quickstart/developer-guide.md
    - Contract Developer Guide: quickstart/contract-developer-guide.md
    - CLI: quickstart/cli.md
  - RPC:
    - RPC Protocol: rpc/rpc-protocol.md
    - JSON-RPC: rpc/json-rpc.md
  - Architecture & Design:
    - Smart Contracts: architecture/smart-contracts.md
    - Microservices: architecture/microservice.md
    - Interprocess Communication: architecture/interprocess-communication.md
    - Serialization: architecture/serialization.md
    - Contract ABI: architecture/contract-abi.md
    - System Calls: architecture/system-calls.md
  - Guides:
    - Using the Faucet on Discord: tutorials/using-the-faucet-on-discord.md
    - Custom Types Contract: tutorials/C++/custom-types-contract.md
    - Deploying a Token: tutorials/deploying-token.md
    - Typescript First Smart Contract: tutorials/AssemblyScript/typescript-first-smart-contract.md