global:
  amqp: amqp://guest:guest@amqp:5672/
  log-level: info
  instance-id: Koinos

block_producer:
  algorithm: pob
  pob-contract-id: 198RuEouhgiiaQm7uGfaXS6jqZr6g6nyoR
  vhp-contract-id: 1JZqj7dDrK5LzvdJgufYBJNUFo88xBoWC8
  # producer:

chain:
  fork-algorithm: block-time

jsonrpc:
  listen: /tcp/8080

p2p:
  listen: /ip4/0.0.0.0/tcp/8888
  peer:
    - /ip4/96.126.102.53/tcp/8888/p2p/QmSbHeJ8TWYu5PbKNhyXu1Jq2fLUKV2UdPasQpqeBwttjr
